### ISSUE TITLE
테이블 정의

### ISSUE THREAD

**Issue by ohrorororong** [zeroback-song/zero-service#4]
테이블 정의하기

* [x] 힙합 테이블 정의하기
* [x] 발라드 테이블 정의하기
* [x] 팝송 테이블 정의하기
* [x] 재즈 테이블 정의하기

**Comment by seongyeong826** [comment]
- [jazz ERD](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Jazz.svg#R7Vttb9o6FP41aLsfWuWlgfbjwugmDbbettukfUEmMYnvnDhyzFt%2F%2FY4Th0ADXSCXF5FISNgnJ345z2M%2F8sG0zG4w%2F8RR5A%2BYi2nL0Nx5y%2FzYMgxdb9%2FBl7QsUkvHNFKDx4mrnHLDE3nByqgp64S4OF5zFIxRQaJ1o8PCEDtizYY4Z7N1tzGj671GyMMFw5ODaNH6k7jCT623lpbbP2Pi%2BVnPuqaeBChzVobYRy6brZnwXNyzUKghPmAeoBCHAp4MEP%2BNecvq%2BULImX5oGffwGUvva48xj2IUkfjaYQGYnRhc7scoIFSGeaUhWzUE3Zm9ltnljIm0FMy7mEqsMhjSMd1vebqMA5ftlnihezVd9H9rIvw8M3%2BIwcB76IyuDDNtZoroRAX4P%2FTyogIkFlnUIVaRLAo0kiY7FogLRQ5TAwPALRAJYWbmRz2pU4qimCTuqcUn1O2jBZuIrKGsZo%2FJHLuPKTekL9CkD43JqmxcRvlJDUY%2BRpR4IZQdmLrs0eY4hrH0USyUR%2FJGOjzdgnoxWCp%2BU8wFnq%2BYVPA%2BYRZgwRfgslw6iiRq4eh3qj7LadjOaOivUNDMGIgUr7xl2zlcUFCI7YLeTQG9rcjB3AVB9BHWJAq9BMR1jGSgXc6iZ8Q9LJQhYkSGuDfF6apI0CCUdhllEuqQhThzS2Zn2fCB%2BXa1a6tlwQC6UNfzOnykOxddFsaCA2VkVxiQm2GJni1YpPqheJwNg6toyvKICQGLrCzOb9P%2B7%2BgvMhDLgn0orK0C1g9fdkGbwWTHNNnwfOK6OExXrdykUc6ADeBuRGSJwmt4Xq%2FVfRG6KY3QCiTmjoioxvIw7dwaorA8QiSwzSahGxdgXo6zAvLtLXu0fM3Qvn4f2L1HWfj2nFT7%2FTOkRbZlp752HCGHhF4%2FfbP9ijfWUXgz376yjf%2BVR6WaOwaROnWWC60CqXaWi%2FbJ5eK2EtbHFIs98OiUxuPixeGugLMgIhnsFHHHR9x4b1jWP5ehDwelyiXrwbehE9Pv%2F1ofDP7LaQ%2FjLxNKroxGDo4kB%2BWPitXlYCPUxWP%2BGe4Bf4fjTRrXSgw2RqKYDpBYxmIYoqCOilCRLrUThGKKoRGEwwiCbpxaEYpJhTPcA%2FZc4lZpOC5dEYonfkRHk6ARhL3YUjtBqJZEaARhB0GwTi0IxUTCGe4Bey7x29JwXLogZD9ivs4XDRchWKUYvNelErh4jCZU%2FvL97uu7MyTCocSgPFNqJwa6XqBOowYHUoPbU6uBXi05eN5yoJe%2F%2FHHxelDMDNIFJ068ejq40TSttseDHchSP0mo9QWko0rC8gLm6SShWnrwzCWhlveNNoeimBrkmMIKwUMXOpaHA%2FgSJMkg1VMSmktG22PTXDI6miTcnFwSLuSW0dtMbiRBLyYHHY6hS3c4WqyeFIw6HxSaq0ZbY5MNo1GFw6tC59SqYFRLFJ63KiyZ3KhCBusKzgFzyZg0srAfYS5IFqCa%2F7Uxdc%2F%2Fj2r2%2FgA%3D)

**Comment by naekang** [comment]
- [발라드 ERD](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=ballad.drawio.svg#R7Zxbb6M4FMc%2FDZrZh1ZcQtI8Lpl0urtJp2pnd6V9iRxwwBqDWePc5tOPDQaSOukQkTSZgBSp%2BHDw5fyPf9CTi2YNwtVnCuJgTDyINVP3Vpr1STNNw7Q6%2FI%2BwrDNLr29lBp8iTzqVhhf0HUqjLq1z5MFky5ERghmKt40uiSLosi0boJQst91mBG%2BPGgMfKoYXF2DV%2Bi%2FyWJBZ72y9tD9A5Af5yIYuz4Qgd5aGJAAeWW6Z4Irdk4jJKT5BGoIIRoyfGQP6DVLNHgaMiZX%2Brpn3%2FDUT3rc%2BIT6GIEbJrUtCbnYT7nI%2FAyHCIswbHTmyIz6cNdSsASWEZUfhagCx0CqXIZvT%2FZ6zRRyo6LfCBYObxXr0TWfRw9L6h43H%2FlNvemNK8RcAz2WAHYAx8GSI2DqPO49WLA4ZmAqTkzBAmUwPS%2BcGLjgDKOJrsz4ZaZv3Eycodc8sAcLeCKzJnOUd5S1nhlbQe86yQ%2FjyRBnxzkRTdC7i%2FCInI04DjPyIH7t88WJEh8KEz2UEEiY91PDIiC0gZXC1YZLh%2BgxJCBldcxd51uzLtJBbxbyT7WWZeIVPsJF0Vk8agcwkv%2Bi7FIgfSI0O0auj6LVXKb52hgB%2B5rsQRH4q2rYmIrAeJfFXQH3IpCEmSIR0uIDZPkijjzAeEEyEtBGJYO6Wrs52%2BIuvd6Df2prNJzDgbaNs85dwp2xAooRRniJiKMiVWkKhlsNILMfBcJZPg8poiuMpYYxvq326vp3YP1dbqmtVFfdk2tqKtk9%2FHaIu4Yud4RRpAfI8GGW7UmAYlIrvEHOnAkXUX8vxei9WVaRTWZENCawDFZCdlWE5uDeAefpHgEGHzCMvUWQt5llD6a6i9DSl7oRfZuqPf4%2Bd4bM4%2BPI1bY5GWnHTuqRMyCmc%2BTpJDFwU%2BaPsyu6rVLFPkiqr%2FZu3e9TUqdTde%2BROr8l3AP2Ud4Du2e8Ad7W0faddXzX%2Bvcrxv3re9xVdGWLpZBeAugGg5kfTtn97hfyLU%2F6nvD9%2Balwz3%2F9nX8LH%2BMGcTIg1%2FW%2F6%2FY8%2Fn70bQ0mVFu%2FHwXv%2FHfG%2BU1rz16T7m2naKLjvjIRaQRHaJWwSgbAJhK%2BZHo0DfKMrOCcFvGGem%2FBqBecC93jFLdzIcs3OSKjVGoCn87DRgG8rNHtD0xZoTgZ4%2B9yA%2F0ULNG%2FmaQv4PeWZyTriVsH2j4YAuwdnYI7Fu8EfHj9coO7HYntbndn%2Ff43ewv1UcK%2F87vqp4G7Uq71dFt2LTG3xbqiFN7ymyE02H947uq435un9gORoHuLVgl6L%2BOMgvvgQ4fkQX6%2F6dmGIry7A1SNerbxRiPkOgBOPD7wJ%2BrvmUL56fjSP8mpRr6X8kSjfOTvl65XgLozy3coCXD3l1fKbSyEf0psAUZYRqGcoLco3A%2FDVU6N5gFeLei3gjwT43rkBn7%2FRex2A71cW4NoBb6oVuJB4aIYaS%2FjqudE4wud7viX8Cb4LdXbC16vCXRbhi0xtCb%2FjC4z5I%2Fx0vVmmMRtUjj8gP5pH%2BXqfqWsp%2Fwbl3%2FMrr7vFrVeFuzDK25UFuHrKqwW44jm%2BwZivniBXhHneLH%2FkInMvf5nEGv4A)

**Comment by donghun93** [comment]
* [힙합 erd](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=hiphop.svg#R7Zzbcps6FIafhml7kQwHYyeXhTrtntptmnS30yuPDDJoVyBGyKc%2B%2FZaMwHZkp3iwY2KY8WRgIeuw%2Fl8fzvJBs9xo8ZGCJBwSH2LN1P2FZn3QTPPGMPhfEVhmga4pAwFFfhbaCDyiP1AGdRmdIh%2BmWw0ZIZihZDvokTiGHtuKAUrJfLvZhODtURMQQCXw6AGsRn8in4VyWba%2Bjn%2BCKAjzkQ1dXolA3lgG0hD4ZL4Vggt2R2Imp3gPaQRiGDN%2BZQjob0g1ux8yJlb6XjPv%2BGMiWl8HhAQYggSl1x6JeNhLeZO7CYgQFmne6MiRHfHhrL5muZQQlh1FCxdiIVUuQzanuz1XizxQ0W%2BJJ7hXs%2BXgt87iT3PrBxsOg%2Fve%2BMq0sm5mAE9lgkOUhCSRKWLLPO88W4k4ZGAsQk7KAGXSHpbOA1xwBlDM12Z9MFbnGIMkRavmWSRE2B%2BAJZmyvKP8zJmgBfQfMneIttwoA96ZOBWdizw%2FysmIywCjIObHHl%2B8GNGhMOVzGYCUyRZqemTGZpAyuNgIyXR9hCSCjC55k%2FyqJW0ht4qR22S%2BNp7Zk7Fww3RWHgTSSUHR91ogfiA1OkSvjqLXXqX42hkC%2BIHvQhAHK9G2NRGJ9SlJvgMaQCYDCUEipf0ZzPbBKvsIY5dgIqSNSQzzZqvV2Q5%2F8PW6%2BrWt2XwCLj831uf8IZpT5pI4ZZRbRAwFuVJzKNRyGHdbNg6Gk3waVGZTHI8JY3xb7dP1eWP%2FXW2prlVW3JNpayva3n8%2BRF3CFzvBK6SFyPdhnO1KgWGwVnyHmDsVKLL%2BVI6ne7GsIp3SimxIYB2ogOxsnZaDewOY2z8GDDpkGvupImsxzwpKd%2FdQd8SfZupf%2Fh06%2FQdx8PX76nQw0IqbVp2ckFM4a%2BukCfBQHAyyZ3afWMU%2BiVUW%2Bzdv56jWKdXdS3in1%2BQ7gH7KO0D37HeAm0ravtCuL5v%2FXun8XzzvbxVdGWKryc4A9UJAzbembb97gvzaKf9X3h%2FfGpfMd%2FMfooMR%2FGH%2BmpP%2FfPLNA2nnylCs0uL9OHi%2FfUG875TWfJ10f9amjYL7zkyoFRShXcpGMYiaQPiK9mgc4BtdwTkp4MvX505FeLWCU8M9XnILN7JcszMTarUG4PE0ajTg2wrN3tS0BZqTAd4%2BN%2BBfaYHmWZ%2B2gN9TnhktYx4VbH9rCLD7cAKmWLwb%2FObLmxrqfiy2t9WZ%2Ff%2FX6C3cTwX3m3PD3ahWe6sX3Quntng31MIbXlLkpZsv3ju6rr%2FTXFN7%2FyrfaT2%2BK5rHdrWS17L9OGwvPj14PrZXK7vVjO3lBbh4tqslNwox3wFw5POBNwl%2F05jizAH%2BaB7l1WpeS%2FkjUb5zdspXq73VjPLd0gJcPOXVuptHIR%2FSHwFRjxGoZyiC%2Bev3hmC%2BvEGah3m1ptdi%2FkiY750b8%2Fn7vJeB%2BdvSAlw65k21ABcRH01Qwzlf3iGN43y%2B81vOn%2BALUWfnfLWKXL04Xzi15fyObzHmL%2BfHy82SjblRk28G6w9wSfNYX%2B3jdS3rn2H9S377dbe41epyNWO9XVqAi2e9WpIrXtM3HvblbXJBsOen61%2B9yJqvf6nE6v8P)

**Comment by LaPo777** [comment]
* [Popsong ERD](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=hiphop.drawio.svg#R7Zzbcps6FIafhml7kQwHYyeXNXXaPbXbNOlup1ceGWTQrpAYIZ%2F69FsywofITvFgx8QwwwUsZEms%2F9cHXj4YjhfPPzKQRAMaQGzYZjA3nA%2BGbVst2zbkZgaLLNK%2B7WSBkKFANVoHHtEfqIKmik5QANOthpxSzFGyHfQpIdDnWzHAGJ1tNxtTvD1qAkKoBR59gPXoTxTwKIveuOY6%2FgmiMMpHtkx1JgZ5YxVIIxDQ2VYIzvkdJVxN8R6yGBBIuDgzAOw3ZIbbiziXV%2FresO%2FENpatr0NKQwxBgtJrn8Yi7Keiyd0YxAjLNG901FUdieGcnuF4jFKe7cVzD2KpVS5DNqe7PWdXeWCy3wIv8K6mi%2F5vk5NPM%2BcHHwzC%2B87oynaybqYAT1SCE5qklIQqR3yRJ16kK5G7HIxkqJtywLjyh2OKgFCcA0TExTkfrOUxxiBJ0bJ5FokQDvpgQSc87yg%2F6o7RHAYPmT1kW%2BGUvuhMHsrOZaIf1WTkaYBRSMS%2BL65ejthlMBVz6YOUqxZ6flTKppBxON8IqXx9hDSGnC1Ek%2Fyso3yh1oqV%2B2S2dp7dUbFow3VOHgTKSuGq77VCYkeJdIhgLU2wvUqJa%2BcI4AexDAEJl6JtayITGzCafAcshFwFEopkSntTmC2EZfYRxh7FVEpLKIF5s%2BXVuV2xiev1zGvXcMUEPHFsrY%2FFJpsz7lGSciYsIoeCQqkZlGp1OU3UOBiO82kwlU25P6Kci3W1T9fnnf13tZW6TlFxT6atq2l7%2F%2FkQdam42DFeMi1CQQBJtiolh8Fa8R1i7lRglfWncjxdi0UVaRVWZEMC50AFVGfrtBzcG8DC%2FgRw2KUTEqSarKt5llC6vQ%2B7Q%2FE62%2Fzy76Dbe5A7X78vD%2Ft9Y3XbqpIVcgxnbbtpAnxEwn72yvYTr7gn8cp8%2F%2BptHdU7hbp7CfN06nwLME95C2if%2FRZwU0rbF1r1RfPfKZz%2Fiwf%2BraYrR3w52SlgfgSY%2FdZ23XdPkF855f%2FK%2B%2BNb45L5bv9DTTCEP%2BxfM%2FpfQL%2F5IG1dWZpVGrwfB%2B%2B3L4j3ndLar5Puz9q0VnDfmQm9hiK1S%2FmQgLgOhC9pj9oBvtYlnJMCvniB7lSE10s4FVzjBZdwLes1OzOhl2sAHk3iWgO%2BqdDsTU1ToDkZ4N1zA%2F6VFmie9WkD%2BD3lmeGCiKhk%2B1tLgj2AYzDB8vPgN1%2FeVFD3Y7G9qc7sf19jNnA%2FFdxvzg13q1ztrVp0Xzm1wbulF97wgiE%2F3Xx4b5mm%2Bc7wbOP9q%2Fyk9fiuqB%2Fb9Upew%2FbjsH31%2FcHzsb1c2a1ibC8uwMWzXS%2B5MYjFCoDDQAy8Sfib2hRnDvBH%2FSivV%2FMayh%2BJ8q2zU75c7a1ilG8XFuDiKa%2FX3XwGxZDBEMh6jEQ9RzHMn99rgvniBqkf5vWaXoP5I2G%2Bc27M55%2FzXgbmbwsLcOmYt%2FUCXEwDNEY153xxh9SO8%2FnKbzh%2Fgl9EnZ3z5Spy1eL8yqkN53f8jDF%2FnB8tNks29kZNvh6sP8Al9WN9ua%2FXNax%2FhvUv%2BfPX3eKWq8tVjPVuYQEunvV6SW71TF972Be3yQXBXhyu%2F%2Fcia77%2BsxKn9z8%3D)
